name: Build Project

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  
jobs:
  Release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build
        shell: bash
        run: '"/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" -property:Configuration=Release'
      
      - name: Upload Artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Release
          path: |
            ./Release/AmongUsMenu.dll
            ./LICENSE
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          files: ./Release/AmongUsMenu.dll
  
  Release_Version:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Build
        shell: bash
        run: '"/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe" -property:Configuration=Release_Version'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          files: ./Release_Version/version.dll
            
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Release_Version/version.dll
